coverage:
  precision: 1
  round: down
  ignore:
  - .*com/github/conda-incubator/condaenvbuilder/cmdline/.*
  status:
    project:
      default:
        enabled: yes
        target: 60%
        threshold: 0.25%
    patch:
      default:
        target: auto

comment:
  layout: "diff"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "docs/**/*"
