name: conda-env-builder unit tests

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        java-version: [8, 11]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('.github/workflows/build.environment.yml') }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.8
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: strict
          environment-file: .github/workflows/build.environment.yml
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - name: Save cache
        uses: coursier/cache-action@v6.3.0
      - name: Unit Tests
        run: |
          git config --add user.name "Mill GithHub Actions"
          git config --add user.email "mill-ci@localhost"
          ./mill --jobs 2 clean
          ./mill --jobs 2 --disable-ticker -s _.compile
          ./mill --jobs 2 --disable-ticker -s tools.test
          ./mill --jobs 2 --disable-ticker -s tools.scoverage.xmlReport
          ./mill --jobs 2 --disable-ticker -s tools.scoverage.htmlReport
          bash <(curl -s https://codecov.io/bash) -c -F tools -f '!*.txt'

  release-github:
    if: github.repository == 'conda-incubator/conda-env-builder' && github.ref == 'refs/heads/main'

    needs: test
    runs-on: ubuntu-latest
    env:
      REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Upload to Github
        run: |
          ./mill uploadToGithub --authKey $REPO_ACCESS_TOKEN
