name: conda-env-builder unit tests

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        java-version: [8, 11]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Conda environment with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          cache-downloads: true
          channels: "conda-forge,defaults"
          environment-file: false
          environment-name: conda-env-builder-test
          extra-specs: "conda-lock=1.4.0"
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - name: Save cache
        uses: coursier/cache-action@v6.3.0
      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Unit Tests
        run: |
          git config --add user.name "Mill GithHub Actions"
          git config --add user.email "mill-ci@localhost"
          ./mill --jobs 2 clean
          ./mill --jobs 2 --disable-ticker -s _.compile
          ./mill --jobs 2 --disable-ticker -s tools.test
          ./mill --jobs 2 --disable-ticker -s tools.scoverage.xmlReport
          ./mill --jobs 2 --disable-ticker -s tools.scoverage.htmlReport
          bash <(curl -s https://codecov.io/bash) -c -F tools -f '!*.txt'

  release-github:
    if: github.repository == 'conda-incubator/conda-env-builder' && github.ref == 'refs/heads/main'

    needs: test
    runs-on: ubuntu-latest
    env:
      REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Upload to Github
        run: |
          ./mill uploadToGithub --authKey $REPO_ACCESS_TOKEN
