name: conda-env-builder unit tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        java-version: [8, 11]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - name: Run '${{ matrix.buildcmd }}'
        run: |
          git config --add user.name "Mill GithHub Actions"
          git config --add user.email "mill-ci@localhost"
          ./mill --jobs 2 clean
          ./mill --jobs 2 --disable-ticker -s _.compile
          ./mill --jobs 2 --disable-ticker -s tools.test
          ./mill --jobs 2 --disable-ticker -s tools.scoverage.xmlReport
          ./mill --jobs 2 --disable-ticker -s tools.scoverage.htmlReport
          bash <(curl -s https://codecov.io/bash) -c -F tools -f '!*.txt'
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            - $HOME/.ivy2/cache
            - $HOME/.cache/coursier
            - $HOME/.cache/mill/download

  release-github:
    if: github.repository == 'nh13/conda-env-builder' && github.ref == 'refs/heads/master'
    needs: test
    strategy:
      matrix:
        buildcmd:
          - if [ "$GITHUB_REPOSITORY" != "nh13/conda-env-builder"]; then echo "Wrong repo: $GITHUB_REPOSITORY"; exit 1; fi
          - if [ "$GITHUB_REF" != "/master"]; then echo "Wrong branch: $GITHUB_REF"; exit 1; fi
          - ./mill uploadToGithub $REPO_ACCESS_TOKEN
    runs-on: ubuntu-latest
    env:
      REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - run: ${{ matrix.buildcmd }}
